/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Main.Main.log;
import static Main.Main.bitacora;
import static Main.Main.bulkLoadingUsers;
import static Main.Main.user;
import static Main.Main.users;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);

        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
        String[] columnas = {"USUARIO", "PASSWORD", "TIMESTAMP"};
        model.setDataVector(users.getUsers(), columnas);

        DefaultTableModel modelIncorrectos = (DefaultTableModel) tablaUsuariosIncorrectos.getModel();
        String[] columnasIncorrectos = {"USUARIO", "DESCRIPCION", "TIMESTAMP"};
        modelIncorrectos.setDataVector(users.getInvalidUsers(), columnasIncorrectos);

        lblCantidadUsuarios.setText(users.getSize() + " USUARIOS");
        lblCantidadUsuariosIncorrectos.setText(users.getInvalidUsers().length + " USUARIOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        opcBitacora = new javax.swing.JMenuItem();
        opcHash = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnLogOff = new java.awt.Button();
        txtCarga2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblCantidadUsuarios = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuariosIncorrectos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblCantidadUsuariosIncorrectos = new javax.swing.JLabel();

        opcBitacora.setText("Reporte Bitacora (Stack)");
        opcBitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcBitacoraMousePressed(evt);
            }
        });
        menu.add(opcBitacora);

        opcHash.setText("Reporte Usuarios (HashTable)");
        opcHash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcHashMousePressed(evt);
            }
        });
        menu.add(opcHash);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("EDD DRIVE /");

        lblUser.setBackground(new java.awt.Color(153, 153, 153));
        lblUser.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(41, 168, 73));
        lblUser.setText("ADMINISTADOR");

        btnLogOff.setActionCommand("Log Off");
        btnLogOff.setBackground(new java.awt.Color(255, 102, 102));
        btnLogOff.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnLogOff.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOff.setLabel("Log Off");
        btnLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOffMouseClicked(evt);
            }
        });

        txtCarga2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtCarga2.setForeground(new java.awt.Color(51, 51, 51));
        txtCarga2.setText("Carga Masiva ...");
        txtCarga2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCarga2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCarga2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCarga2MouseExited(evt);
            }
        });

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "PASSWORD", "TIMESTAMP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("USUARIOS REGISTRADOS /");

        lblCantidadUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        lblCantidadUsuarios.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblCantidadUsuarios.setForeground(new java.awt.Color(41, 168, 73));
        lblCantidadUsuarios.setText("1000 USUARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadUsuarios)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCantidadUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("USUARIOS REGISTRADOS", jPanel2);

        tablaUsuariosIncorrectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "PASSWORD", "TIMESTAMP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuariosIncorrectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaUsuariosIncorrectosMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaUsuariosIncorrectos);
        if (tablaUsuariosIncorrectos.getColumnModel().getColumnCount() > 0) {
            tablaUsuariosIncorrectos.getColumnModel().getColumn(0).setResizable(false);
            tablaUsuariosIncorrectos.getColumnModel().getColumn(1).setResizable(false);
            tablaUsuariosIncorrectos.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("USUARIOS NO REGISTRADOS /");

        lblCantidadUsuariosIncorrectos.setBackground(new java.awt.Color(153, 153, 153));
        lblCantidadUsuariosIncorrectos.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblCantidadUsuariosIncorrectos.setForeground(new java.awt.Color(41, 168, 73));
        lblCantidadUsuariosIncorrectos.setText("1000 USUARIOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadUsuariosIncorrectos)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCantidadUsuariosIncorrectos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("USUARIOS CON ERROR", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCarga2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblUser)
                        .addComponent(txtCarga2)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOffMouseClicked
        this.setVisible(false);
        log.setVisible(true);
        bitacora.add(user.getUsuario(), "Cerro Sesion ");
    }//GEN-LAST:event_btnLogOffMouseClicked

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if (evt.isPopupTrigger()) {
            menu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void opcBitacoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcBitacoraMousePressed

        try {
            bitacora.graph();
            new Reporte("stack.png").setVisible(true);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_opcBitacoraMousePressed

    private void opcHashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcHashMousePressed
        try {
            users.graph();
            new Reporte("hashTable.png").setVisible(true);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opcHashMousePressed

    private void txtCarga2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCarga2MouseClicked

        try {
            //ABRIR EL ARCHIVO CSV
            JFileChooser jfc = new JFileChooser();
            jfc.addChoosableFileFilter(new FileNameExtensionFilter("CSV File", "csv"));
            jfc.showOpenDialog(this);

            File f = jfc.getSelectedFile();

            if (f.exists() && f.getName().contains(".csv")) {
                System.out.println(f.getName());

                FileReader fr = new FileReader(f.getAbsolutePath());
                BufferedReader br = new BufferedReader(fr);

                String line = "";
                String[] headers = br.readLine().toLowerCase().strip().split(",");

                if (headers.length == 2) {
                    String h1 = headers[0];
                    String h2 = headers[1];

                    if ((h1.contains("usuario") && h2.contains("password")) || (h2.contains("usuario")) && h1.contains("password")) {

                        JOptionPane.showMessageDialog(null, "Se cargo el CSV");
                        bulkLoadingUsers(f.getAbsolutePath());

                        tablaUsuarios.removeAll();
                        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
                        String[] columnas = {"USUARIO", "PASSWORD", "TIMESTAMP"};
                        model.setDataVector(users.getUsers(), columnas);
                        tablaUsuarios.repaint();
                        
                        tablaUsuariosIncorrectos.removeAll();
                        DefaultTableModel modelIncorrectos = (DefaultTableModel) tablaUsuariosIncorrectos.getModel();
                        String[] columnasIncorrectos = {"USUARIO", "DESCRIPCION", "TIMESTAMP"};
                        modelIncorrectos.setDataVector(users.getInvalidUsers(), columnasIncorrectos);
                        tablaUsuariosIncorrectos.repaint();

                        lblCantidadUsuarios.setText(users.getSize() + " USUARIOS");
                        lblCantidadUsuariosIncorrectos.setText(users.getInvalidUsers().length + " USUARIOS");

                    } else {
                        JOptionPane.showMessageDialog(null, "El archivo no cumple con la estructura solicitada, las columnas no son usuario y password");
                    }

                    br.close();
                    fr.close();
                } else {
                    JOptionPane.showMessageDialog(null, "El archivo no cumple con la estructura solicitada, tiene más de 2 columnas");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Abra un archivo con extension csv");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el archivo que seleccionaste");
        }


    }//GEN-LAST:event_txtCarga2MouseClicked

    private void txtCarga2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCarga2MouseEntered
        txtCarga2.setForeground(new Color(41, 168, 73));
    }//GEN-LAST:event_txtCarga2MouseEntered

    private void txtCarga2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCarga2MouseExited
        txtCarga2.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_txtCarga2MouseExited

    private void tablaUsuariosIncorrectosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosIncorrectosMouseReleased
        if (evt.isPopupTrigger()) {
            menu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tablaUsuariosIncorrectosMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLogOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCantidadUsuarios;
    private javax.swing.JLabel lblCantidadUsuariosIncorrectos;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JMenuItem opcBitacora;
    private javax.swing.JMenuItem opcHash;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTable tablaUsuariosIncorrectos;
    private javax.swing.JLabel txtCarga;
    private javax.swing.JLabel txtCarga1;
    private javax.swing.JLabel txtCarga2;
    // End of variables declaration//GEN-END:variables
}
