/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author aybso
 */
import static Main.Main.*;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.DirectoryStream.Filter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreeSelectionModel;

public class UserDashboard extends javax.swing.JFrame {

    //----------------------
    DefaultMutableTreeNode selectedNode;

    //----------------------
    public UserDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        lblUser.setText(user.getUsuario().toUpperCase());

        treeFolders.setEditable(true);
        selectedNode = (DefaultMutableTreeNode) treeFolders.getModel().getRoot();
        selectedNode = (DefaultMutableTreeNode) selectedNode.getRoot();
        
        n.imprimirDirectorioCompleto();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnLogOff = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeFolders = new javax.swing.JTree(n.getTreeRoot());
        lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEliminarFolder = new java.awt.Button();
        btnCrearFolder = new java.awt.Button();
        btnModificarFolder = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEliminarArchivo = new java.awt.Button();
        btnCrearArchivo = new java.awt.Button();
        btnAbrirArchivo = new java.awt.Button();
        btnCompartirArchivo = new java.awt.Button();
        btnModificarArchivo = new java.awt.Button();
        btnDescargarArchivo = new java.awt.Button();
        txtCarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("EDD DRIVE /");

        lblUser.setBackground(new java.awt.Color(153, 153, 153));
        lblUser.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(41, 168, 73));
        lblUser.setText("USER");

        btnLogOff.setActionCommand("Log Off");
        btnLogOff.setBackground(new java.awt.Color(255, 102, 102));
        btnLogOff.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnLogOff.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOff.setLabel("Log Off");
        btnLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOffMouseClicked(evt);
            }
        });

        treeFolders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeFoldersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeFolders);

        lbl.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl.setForeground(new java.awt.Color(41, 168, 73));
        lbl.setText("/");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(463, 221));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Carpetas");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        btnEliminarFolder.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminarFolder.setEnabled(false);
        btnEliminarFolder.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFolder.setLabel("Eliminar");
        btnEliminarFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarFolderMouseClicked(evt);
            }
        });

        btnCrearFolder.setBackground(new java.awt.Color(41, 168, 73));
        btnCrearFolder.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearFolder.setLabel("Crear");
        btnCrearFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearFolderMouseClicked(evt);
            }
        });

        btnModificarFolder.setBackground(new java.awt.Color(153, 153, 153));
        btnModificarFolder.setEnabled(false);
        btnModificarFolder.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarFolder.setLabel("Modificar");
        btnModificarFolder.setName(""); // NOI18N
        btnModificarFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarFolderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEliminarFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(btnModificarFolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(btnCrearFolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnCrearFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnModificarFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnEliminarFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Archivos");

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));

        btnEliminarArchivo.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminarArchivo.setEnabled(false);
        btnEliminarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarArchivo.setLabel("Eliminar");
        btnEliminarArchivo.setName(""); // NOI18N

        btnCrearArchivo.setBackground(new java.awt.Color(41, 168, 73));
        btnCrearArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearArchivo.setLabel("Crear");

        btnAbrirArchivo.setBackground(new java.awt.Color(153, 153, 153));
        btnAbrirArchivo.setEnabled(false);
        btnAbrirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirArchivo.setLabel("Abrir");

        btnCompartirArchivo.setBackground(new java.awt.Color(153, 153, 153));
        btnCompartirArchivo.setEnabled(false);
        btnCompartirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCompartirArchivo.setLabel("Compartir");
        btnCompartirArchivo.setName(""); // NOI18N

        btnModificarArchivo.setBackground(new java.awt.Color(153, 153, 153));
        btnModificarArchivo.setEnabled(false);
        btnModificarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarArchivo.setLabel("Modificar");

        btnDescargarArchivo.setBackground(new java.awt.Color(153, 153, 153));
        btnDescargarArchivo.setEnabled(false);
        btnDescargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargarArchivo.setLabel("Descargar");

        txtCarga.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtCarga.setForeground(new java.awt.Color(51, 51, 51));
        txtCarga.setText("Carga Masiva ...");
        txtCarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCargaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAbrirArchivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarArchivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(btnCrearArchivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDescargarArchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCompartirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnModificarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCarga, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDescargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrearArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnModificarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarArchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCompartirArchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btnAbrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeFoldersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeFoldersMouseClicked

        TreeSelectionModel model = treeFolders.getSelectionModel();
        if (model.getSelectionCount() > 0) {
            selectedNode = (DefaultMutableTreeNode) treeFolders.getSelectionPath().getLastPathComponent();

            TreeNode[] path = selectedNode.getPath();
            String path_string = "";
            for (TreeNode node : path) {
                path_string += node.toString() + "/";
            }
            lbl.setText(path_string);

            if (path[path.length - 1].toString().contains(".")) {
                enabledFilesButtons();
                disabledAllFoldersButtons();
            } else {
                enabledFoldersButtons();
                disabledAllFileButtons();
            }
            
            if(lbl.getText().equals("/")){
                disabledAllFoldersButtons();
                disabledAllFileButtons();
            }

        } else {
            disabledAllFoldersButtons();
            disabledAllFileButtons();
        }


    }//GEN-LAST:event_treeFoldersMouseClicked

    private void btnCrearFolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFolderMouseClicked

        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(JOptionPane.showInputDialog(null, "Nombre del Folder"));
        selectedNode.add(newNode);

        DefaultTreeModel model = (DefaultTreeModel) treeFolders.getModel();
        model.reload();

        disabledAllFoldersButtons();
    }//GEN-LAST:event_btnCrearFolderMouseClicked

    private void btnModificarFolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarFolderMouseClicked
        if (!lbl.getText().equals("/")) {
            TreeNode[] path = selectedNode.getPath();
            String folderName = path[path.length - 1].toString();

            String newFolderName = JOptionPane.showInputDialog(null, "Ingresa el nombre del folder: ", folderName);

            if (!newFolderName.isBlank() && !newFolderName.equals(folderName)) {
                selectedNode.setUserObject(newFolderName);
                DefaultTreeModel model = (DefaultTreeModel) treeFolders.getModel();
                model.reload();

                disabledAllFoldersButtons();
                disabledAllFileButtons();
            }

        }
    }//GEN-LAST:event_btnModificarFolderMouseClicked

    private void btnEliminarFolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFolderMouseClicked
        if (!lbl.getText().equals("/")) {
            TreeNode[] path = selectedNode.getPath();
            String folderName = path[path.length - 1].toString();

            int estasSeguro = JOptionPane.showConfirmDialog(null, "¿Seguro deseas eliminar " + folderName + "?", "Eliminar Carpeta", JOptionPane.YES_NO_OPTION);

            if (estasSeguro == JOptionPane.OK_OPTION) {
                DefaultTreeModel model = (DefaultTreeModel) treeFolders.getModel();
                model.removeNodeFromParent(selectedNode);
                model.reload();

                selectedNode = (DefaultMutableTreeNode) treeFolders.getModel().getRoot();
                selectedNode = (DefaultMutableTreeNode) selectedNode.getRoot();

                disabledAllFoldersButtons();
                disabledAllFileButtons();
            }

        }
    }//GEN-LAST:event_btnEliminarFolderMouseClicked

    private void txtCargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargaMouseEntered
        txtCarga.setForeground(new Color(41, 168, 73));
    }//GEN-LAST:event_txtCargaMouseEntered

    private void txtCargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargaMouseExited
        txtCarga.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_txtCargaMouseExited

    private void txtCargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargaMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.addChoosableFileFilter(new FileNameExtensionFilter("CSV File", "csv"));
        jfc.showOpenDialog(this);

        File f = jfc.getSelectedFile();

        if (f.exists()) {
            System.out.println("El archivo existe");
        } else {
            System.out.println("El archivo no existe");
        }


    }//GEN-LAST:event_txtCargaMouseClicked

    private void btnLogOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOffMouseClicked
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_btnLogOffMouseClicked

    private void disabledAllFileButtons() {
        btnModificarArchivo.setEnabled(false);
        btnEliminarArchivo.setEnabled(false);
        btnCompartirArchivo.setEnabled(false);
        btnAbrirArchivo.setEnabled(false);
        btnDescargarArchivo.setEnabled(false);

        btnModificarArchivo.setBackground(new Color(153, 153, 153));
        btnEliminarArchivo.setBackground(new Color(153, 153, 153));
        btnCompartirArchivo.setBackground(new Color(153, 153, 153));
        btnAbrirArchivo.setBackground(new Color(153, 153, 153));
        btnDescargarArchivo.setBackground(new Color(153, 153, 153));
    }

    private void disabledAllFoldersButtons() {
        btnModificarFolder.setEnabled(false);
        btnEliminarFolder.setEnabled(false);
        btnModificarFolder.setBackground(new Color(153, 153, 153));
        btnEliminarFolder.setBackground(new Color(153, 153, 153));
    }

    private void enabledFoldersButtons() {
        btnModificarFolder.setEnabled(true);
        btnEliminarFolder.setEnabled(true);
        btnModificarFolder.setBackground(new Color(41, 168, 73));
        btnEliminarFolder.setBackground(new Color(41, 168, 73));
    }

    private void enabledFilesButtons() {
        btnModificarArchivo.setEnabled(true);
        btnEliminarArchivo.setEnabled(true);
        btnCompartirArchivo.setEnabled(true);
        btnAbrirArchivo.setEnabled(true);
        btnDescargarArchivo.setEnabled(true);

        btnModificarArchivo.setBackground(new Color(41, 168, 73));
        btnEliminarArchivo.setBackground(new Color(41, 168, 73));
        btnCompartirArchivo.setBackground(new Color(41, 168, 73));
        btnAbrirArchivo.setBackground(new Color(41, 168, 73));
        btnDescargarArchivo.setBackground(new Color(41, 168, 73));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAbrirArchivo;
    private java.awt.Button btnCompartirArchivo;
    private java.awt.Button btnCrearArchivo;
    private java.awt.Button btnCrearFolder;
    private java.awt.Button btnDescargarArchivo;
    private java.awt.Button btnEliminarArchivo;
    private java.awt.Button btnEliminarFolder;
    private java.awt.Button btnLogOff;
    private java.awt.Button btnModificarArchivo;
    private java.awt.Button btnModificarFolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTree treeFolders;
    private javax.swing.JLabel txtCarga;
    // End of variables declaration//GEN-END:variables
}
